events {
    worker_connections 4096;
}

http {
    upstream servers {
        server server-1:8000;
        server server-2:8000;
        server server-3:8000;
        server server-4:8000;
    }

    server {
        listen 80;
        server_name shurl.kdmarc.xyz;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name shurl.kdmarc.xyz;

        ssl_certificate /etc/letsencrypt/live/shurl.kdmarc.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/shurl.kdmarc.xyz/privkey.pem;

        location / {
            proxy_pass http://servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}